package Pojos;
// Generated 22/05/2014 02:26:34 PM by Hibernate Tools 3.2.1.GA



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombre;
     private String apeliidoPaterno;
     private String apellidoMaterno;
     private String email;
     private String password;
     private String telefono;

    public Cliente() {
    }

	
    public Cliente(String nombre, String apeliidoPaterno, String apellidoMaterno, String email, String password) {
        this.nombre = nombre;
        this.apeliidoPaterno = apeliidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.email = email;
        this.password = password;
    }
    public Cliente(String nombre, String apeliidoPaterno, String apellidoMaterno, String email, String password, String telefono) {
       this.nombre = nombre;
       this.apeliidoPaterno = apeliidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.email = email;
       this.password = password;
       this.telefono = telefono;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApeliidoPaterno() {
        return this.apeliidoPaterno;
    }
    
    public void setApeliidoPaterno(String apeliidoPaterno) {
        this.apeliidoPaterno = apeliidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


