package Pojos;
// Generated 22/05/2014 02:26:34 PM by Hibernate Tools 3.2.1.GA



/**
 * Constructora generated by hbm2java
 */
public class Constructora  implements java.io.Serializable {


     private Integer idConstructora;
     private String nombre;
     private String password;
     private String descripcion;
     private String email;
     private String telefono;
     private String direccion;
     private String logotipo;

    public Constructora() {
    }

    public Constructora(String nombre, String password, String descripcion, String email, String telefono, String direccion, String logotipo) {
       this.nombre = nombre;
       this.password = password;
       this.descripcion = descripcion;
       this.email = email;
       this.telefono = telefono;
       this.direccion = direccion;
       this.logotipo = logotipo;
    }
   
    public Integer getIdConstructora() {
        return this.idConstructora;
    }
    
    public void setIdConstructora(Integer idConstructora) {
        this.idConstructora = idConstructora;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLogotipo() {
        return this.logotipo;
    }
    
    public void setLogotipo(String logotipo) {
        this.logotipo = logotipo;
    }




}


