package Pojos;
// Generated 22/05/2014 02:26:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idProyecto;
     private String nombre;
     private int idCliente;
     private Date fechaInicio;
     private Date fechaTermino;
     private String estatus;
     private String descripcion;
     private int idConstructoraTipoProyecto;
     private Integer ranking;
     private String fotografia;

    public Proyecto() {
    }

	
    public Proyecto(String nombre, int idCliente, Date fechaInicio, Date fechaTermino, String estatus, String descripcion, int idConstructoraTipoProyecto) {
        this.nombre = nombre;
        this.idCliente = idCliente;
        this.fechaInicio = fechaInicio;
        this.fechaTermino = fechaTermino;
        this.estatus = estatus;
        this.descripcion = descripcion;
        this.idConstructoraTipoProyecto = idConstructoraTipoProyecto;
    }
    public Proyecto(String nombre, int idCliente, Date fechaInicio, Date fechaTermino, String estatus, String descripcion, int idConstructoraTipoProyecto, Integer ranking, String fotografia) {
       this.nombre = nombre;
       this.idCliente = idCliente;
       this.fechaInicio = fechaInicio;
       this.fechaTermino = fechaTermino;
       this.estatus = estatus;
       this.descripcion = descripcion;
       this.idConstructoraTipoProyecto = idConstructoraTipoProyecto;
       this.ranking = ranking;
       this.fotografia = fotografia;
    }
   
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaTermino() {
        return this.fechaTermino;
    }
    
    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getIdConstructoraTipoProyecto() {
        return this.idConstructoraTipoProyecto;
    }
    
    public void setIdConstructoraTipoProyecto(int idConstructoraTipoProyecto) {
        this.idConstructoraTipoProyecto = idConstructoraTipoProyecto;
    }
    public Integer getRanking() {
        return this.ranking;
    }
    
    public void setRanking(Integer ranking) {
        this.ranking = ranking;
    }
    public String getFotografia() {
        return this.fotografia;
    }
    
    public void setFotografia(String fotografia) {
        this.fotografia = fotografia;
    }




}


