package Pojos;
// Generated 22/05/2014 02:26:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ServicioContratado generated by hbm2java
 */
public class ServicioContratado  implements java.io.Serializable {


     private Integer idServicioContratado;
     private String nombre;
     private Integer costo;
     private Date fechaContratacion;
     private Integer idProyecto;
     private String nota;

    public ServicioContratado() {
    }

	
    public ServicioContratado(String nombre) {
        this.nombre = nombre;
    }
    public ServicioContratado(String nombre, Integer costo, Date fechaContratacion, Integer idProyecto, String nota) {
       this.nombre = nombre;
       this.costo = costo;
       this.fechaContratacion = fechaContratacion;
       this.idProyecto = idProyecto;
       this.nota = nota;
    }
   
    public Integer getIdServicioContratado() {
        return this.idServicioContratado;
    }
    
    public void setIdServicioContratado(Integer idServicioContratado) {
        this.idServicioContratado = idServicioContratado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCosto() {
        return this.costo;
    }
    
    public void setCosto(Integer costo) {
        this.costo = costo;
    }
    public Date getFechaContratacion() {
        return this.fechaContratacion;
    }
    
    public void setFechaContratacion(Date fechaContratacion) {
        this.fechaContratacion = fechaContratacion;
    }
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }




}


