package Pojos;
// Generated 22/05/2014 02:26:34 PM by Hibernate Tools 3.2.1.GA



/**
 * ServicioPropuesto generated by hbm2java
 */
public class ServicioPropuesto  implements java.io.Serializable {


     private Integer idServicioPropuesto;
     private int idConstructoraTipoProyecto;
     private int idServicio;
     private Integer costo;

    public ServicioPropuesto() {
    }

	
    public ServicioPropuesto(int idConstructoraTipoProyecto, int idServicio) {
        this.idConstructoraTipoProyecto = idConstructoraTipoProyecto;
        this.idServicio = idServicio;
    }
    public ServicioPropuesto(int idConstructoraTipoProyecto, int idServicio, Integer costo) {
       this.idConstructoraTipoProyecto = idConstructoraTipoProyecto;
       this.idServicio = idServicio;
       this.costo = costo;
    }
   
    public Integer getIdServicioPropuesto() {
        return this.idServicioPropuesto;
    }
    
    public void setIdServicioPropuesto(Integer idServicioPropuesto) {
        this.idServicioPropuesto = idServicioPropuesto;
    }
    public int getIdConstructoraTipoProyecto() {
        return this.idConstructoraTipoProyecto;
    }
    
    public void setIdConstructoraTipoProyecto(int idConstructoraTipoProyecto) {
        this.idConstructoraTipoProyecto = idConstructoraTipoProyecto;
    }
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public Integer getCosto() {
        return this.costo;
    }
    
    public void setCosto(Integer costo) {
        this.costo = costo;
    }




}


